In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('schedule_outputput_all.csv',encoding='UTF8')

In [7]:
df.head()

,date,opposition,result,batter_no,position,is_starter,AB,R,H,2B,...,OPS,투구,avLi,RE24,WPA,year,cur_team,team,batter_name,year_born
0,03-24,@NC,L 2:4,4,3B,1,3,1,1,0,...,0.833,15,1.17,0.52,0.043,2018,LG,LG,가르시아,1985-04-12
1,03-25,@NC,L 1:7,4,3B,1,4,0,0,0,...,0.393,13,0.66,-1.08,-0.065,2018,LG,LG,가르시아,1985-04-12
2,03-27,@넥센,L 4:5,4,3B,1,5,0,1,0,...,0.397,15,1.49,-0.78,-0.039,2018,LG,LG,가르시아,1985-04-12
3,03-28,@넥센,W 9:3,4,3B,1,5,1,1,0,...,0.399,10,0.65,-0.36,0.061,2018,LG,LG,가르시아,1985-04-12
4,03-29,@넥센,L 4:9,4,3B,1,4,0,1,0,...,0.408,14,0.61,-0.53,-0.032,2018,LG,LG,가르시아,1985-04-12

In [8]:
df.columns

Index(['date', 'opposition', 'result', 'batter_no', 'position', 'is_starter',
       'AB', 'R', 'H', '2B', '3B', 'HR', 'TB', 'RBI', 'SB', 'CS', 'BB', 'HBP',
       'IBB', 'K', 'GDP', 'SH', 'SF', 'avg2', 'OBP', 'SLG', 'OPS', '투구',
       'avLi', 'RE24', 'WPA', 'year', 'cur_team', 'team', 'batter_name',
       'year_born'],
      dtype='object')

In [11]:
df[[ 'batter_name',
       'year_born','year',  'team', 'cur_team','date', 'opposition', 'result', 'batter_no', 'position', 'is_starter',
       'AB', 'R', 'H', '2B', '3B', 'HR', 'TB', 'RBI', 'SB', 'CS', 'BB', 'HBP',
       'IBB', 'K', 'GDP', 'SH', 'SF', 'avg2', 'OBP', 'SLG', 'OPS', '투구',
       'avLi', 'RE24', 'WPA']]

,batter_name,year_born,year,team,cur_team,date,opposition,result,batter_no,position,...,SH,SF,avg2,OBP,SLG,OPS,투구,avLi,RE24,WPA
0,가르시아,1985-04-12,2018,LG,LG,03-24,@NC,L 2:4,4,3B,...,0,0,0.333,0.500,0.333,0.833,15,1.17,0.52,0.043
1,가르시아,1985-04-12,2018,LG,LG,03-25,@NC,L 1:7,4,3B,...,0,0,0.143,0.250,0.143,0.393,13,0.66,-1.08,-0.065
2,가르시아,1985-04-12,2018,LG,LG,03-27,@넥센,L 4:5,4,3B,...,0,0,0.167,0.231,0.167,0.397,15,1.49,-0.78,-0.039
3,가르시아,1985-04-12,2018,LG,LG,03-28,@넥센,W 9:3,4,3B,...,0,0,0.176,0.222,0.176,0.399,10,0.65,-0.36,0.061
4,가르시아,1985-04-12,2018,LG,LG,03-29,@넥센,L 4:9,4,3B,...,0,1,0.190,0.217,0.190,0.408,14,0.61,-0.53,-0.032
5,가르시아,1985-04-12,2018,LG,LG,03-30,KIA,L 3:4,4,3B,...,0,0,0.269,0.286,0.308,0.593,20,2.79,0.96,-0.017
6,가르시아,1985-04-12,2018,LG,LG,03-31,KIA,W 6:4,4,3B,...,0,1,0.345,0.344,0.414,0.758,10,1.01,1.81,0.197
7,가르시아,1985-04-12,2018,LG,LG,04-01,KIA,W 6:5,4,3B,...,0,0,0.394,0.405,0.455,0.860,14,1.99,1.70,0.503
8,가르시아,1985-04-12,2018,LG,LG,04-03,@두산,L 4:5,4,3B,...,0,0,0.395,0.419,0.526,0.945,25,2.80,0.29,-0.067
9,가르시아,1985-04-12,2018,LG,LG,04-04,@두산,L 3:6,4,3B,...,0,0,0.405,0.426,0.524,0.949,12,1.25,0.01,0.026
10,가르시아,1985-04-12,2018,LG,LG,04-06,@롯데,W 14:6,4,3B,...,0,0,0.435,0.472,0.674,1.146,22,0.32,4.42,0.216
11,가르시아,1985-04-12,2018,LG,LG,04-07,@롯데,L 2:7,4,3B,...,0,0,0.429,0.474,0.653,1.127,18,0.91,-0.07,-0.024
12,가르시아,1985-04-12,2018,LG,LG,04-08,@롯데,W 4:2,4,3B,...,0,0,0.404,0.459,0.615,1.074,13,1.48,-0.63,-0.102
13,가르시아,1985-04-12,2018,LG,LG,04-10,SK,L 1:4,4,3B,...,0,0,0.393,0.446,0.589,1.035,16,1.32,-0.36,-0.002
14,가르시아,1985-04-12,2018,LG,LG,04-11,SK,W 3:0,4,3B,...,0,0,0.373,0.426,0.559,0.986,18,1.09,-1.02,-0.078
15,가르시아,1985-04-12,2018,LG,LG,04-12,SK,W 5:4,4,3B,...,0,0,0.371,0.431,0.548,0.979,8,0.68,0.23,0.038
16,가르시아,1985-04-12,2018,LG,LG,04-13,KT,W 3:1,4,3B,...,0,0,0.359,0.427,0.531,0.958,10,0.60,0.42,0.034
17,가르시아,1985-04-12,2018,LG,LG,04-14,KT,W 8:0,4,3B,...,0,0,0.338,0.405,0.500,0.905,18,0.43,-1.20,-0.043
18,가르시아,1985-04-12,2018,LG,LG,04-15,KT,W 11:8,4,3B,...,0,1,0.361,0.417,0.528,0.944,12,0.39,0.60,0.069
19,가르시아,1985-04-12,2018,LG,LG,04-17,@KIA,L 4:5,4,3B,...,0,0,0.356,0.412,0.521,0.932,3,1.93,-0.43,-0.038
20,가르시아,1985-04-12,2018,LG,LG,07-11,SK,W 3:1,7,PH,...,0,0,0.365,0.419,0.527,0.946,2,1.06,-0.51,-0.024
21,가르시아,1985-04-12,2018,LG,LG,07-12,SK,L 4:7,6,PH,...,0,0,0.364,0.416,0.558,0.974,8,1.77,-0.11,-0.078
22,가르시아,1985-04-12,2018,LG,LG,07-17,@넥센,W 9:3,5,3B,...,0,0,0.366,0.415,0.549,0.964,24,0.80,0.26,-0.085
23,가르시아,1985-04-12,2018,LG,LG,07-18,@넥센,W 8:7,5,3B,...,0,0,0.365,0.418,0.553,0.971,17,1.31,0.39,0.015
24,가르시아,1985-04-12,2018,LG,LG,07-20,두산,L 4:5,5,3B,...,0,0,0.374,0.423,0.560,0.984,24,1.74,0.77,0.216
25,가르시아,1985-04-12,2018,LG,LG,07-21,두산,L 10:17,3,3B,...,0,0,0.385,0.436,0.563,0.999,17,0.22,0.67,0.046
26,가르시아,1985-04-12,2018,LG,LG,07-22,두산,L 1:6,3,3B,...,0,0,0.370,0.421,0.540,0.961,16,1.08,-0.96,-0.092
27,가르시아,1985-04-12,2018,LG,LG,07-24,삼성,L 1:11,3,3B,...,0,0,0.365,0.415,0.529,0.944,11,0.19,-0.47,-0.019
28,가르시아,1985-04-12,2018,LG,LG,07-25,삼성,L 0:1,3,3B,...,0,0,0.352,0.402,0.509,0.911,14,2.06,-1.11,-0.232
29,가르시아,1985-04-12,2018,LG,LG,07-26,삼성,W 7:5,3,3B,...,0,0,0.366,0.413,0.545,0.957,12,1.24,2.88,0.182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78274,황진수,1989-02-15,2017,롯데,롯데,09-13,@LG,L 1:3,9,3B,...,0,0,0.269,0.337,0.376,0.713,0,0.00,0.00,0.000
78275,황진수,1989-02-15,2017,롯데,롯데,09-14,KIA,L 2:11,7,3B,...,0,0,0.266,0.333,0.372,0.706,2,0.00,-0.23,0.000
78276,황진수,1989-02-15,2017,롯데,롯데,09-15,KIA,W 4:3,9,3B,...,0,0,0.268,0.333,0.371,0.704,13,1.40,0.17,-0.040
78277,황진수,1989-02-15,2017,롯데,롯데,09-16,SK,W 6:1,9,3B,...,0,0,0.270,0.333,0.370,0.703,7,0.87,-0.48,0.034
78278,황진수,1989-02-15,2017,롯데,롯데,09-17,SK,W 9:5,9,3B,...,0,0,0.272,0.333,0.398,0.731,15,0.78,2.02,0.061
78279,황진수,1989-02-15,2017,롯데,롯데,09-19,두산,L 3:8,9,3B,...,0,0,0.267,0.328,0.390,0.718,5,0.64,-0.58,-0.032
78280,황진수,1989-02-15,2017,롯데,롯데,09-22,@한화,W 2:0,9,3B,...,1,0,0.271,0.331,0.393,0.723,6,0.97,-0.47,-0.024
78281,황진수,1989-02-15,2017,롯데,롯데,09-23,넥센,W 7:2,9,3B,...,0,0,0.282,0.339,0.400,0.739,10,0.78,0.17,0.027
78282,황진수,1989-02-15,2017,롯데,롯데,09-26,한화,W 11:8,9,3B,...,0,0,0.288,0.360,0.405,0.765,22,1.43,1.33,0.112
78283,황진수,1989-02-15,2017,롯데,롯데,09-29,@SK,W 7:2,9,3B,...,0,0,0.296,0.364,0.409,0.773,15,0.62,1.69,0.100
78284,황진수,1989-02-15,2017,롯데,롯데,10-03,LG,W 4:2,9,3B,...,0,0,0.291,0.359,0.402,0.760,4,1.94,-0.24,0.007
78285,황진수,1989-02-15,2017,롯데,롯데,10-08,NC,L 2:9,9,3B,...,0,0,0.000,0.000,0.000,0.000,16,1.45,-1.10,-0.150
78286,황진수,1989-02-15,2017,롯데,롯데,10-15,NC,L 0:9,3,PH,...,0,0,0.167,0.167,0.333,0.500,4,0.01,0.43,0.001
78287,황진수,1989-02-15,2018,롯데,롯데,04-18,삼성,W 9:7,7,PH,...,0,0,0.000,0.000,0.000,0.000,9,2.26,-0.52,-0.115
78288,황진수,1989-02-15,2018,롯데,롯데,04-19,삼성,L 0:6,7,3B,...,0,0,0.000,0.000,0.000,0.000,7,0.72,-0.44,-0.036
78289,황진수,1989-02-15,2018,롯데,롯데,04-20,SK,W 10:5,3,1B,...,0,0,0.000,0.000,0.000,0.000,0,0.00,0.00,0.000
78290,황진수,1989-02-15,2018,롯데,롯데,04-24,@KT,W 14:8,4,PR,...,0,0,0.000,0.000,0.000,0.000,0,0.00,0.00,0.000
78291,황진수,1989-02-15,2018,롯데,롯데,04-25,@KT,W 5:4,9,PR,...,0,0,0.000,0.000,0.000,0.000,0,0.00,0.00,0.000
78292,황진수,1989-02-15,2018,롯데,롯데,04-28,한화,L 2:4,2,3B,...,0,0,0.000,0.000,0.000,0.000,8,1.52,-1.18,-0.115
78293,황진수,1989-02-15,2018,롯데,롯데,06-14,삼성,L 9:11,7,3B,...,0,0,0.083,0.083,0.083,0.167,18,0.98,-1.04,-0.114
78294,황진수,1989-02-15,2018,롯데,롯데,06-15,@SK,W 14:6,7,3B,...,0,0,0.083,0.083,0.083,0.167,0,0.00,0.00,0.000
78295,황진수,1989-02-15,2018,롯데,롯데,06-16,@SK,W 9:3,9,PR,...,0,0,0.083,0.083,0.083,0.167,0,0.00,0.00,0.000
78296,황진수,1989-02-15,2018,롯데,롯데,06-19,@KT,W 9:7,7,3B,...,0,0,0.188,0.188,0.375,0.563,18,0.89,0.61,0.229
78297,황진수,1989-02-15,2018,롯데,롯데,06-20,@KT,W 11:4,8,3B,...,0,0,0.188,0.235,0.375,0.610,5,0.02,0.72,0.001
78298,황진수,1989-02-15,2018,롯데,롯데,06-21,@KT,D 5:5,9,PH,...,0,0,0.167,0.211,0.333,0.544,6,2.68,-0.58,-0.132
78299,황진수,1989-02-15,2018,롯데,롯데,06-22,@LG,L 1:2,9,PH,...,0,0,0.158,0.200,0.316,0.516,3,1.73,-0.26,-0.044
78300,황진수,1989-02-15,2018,롯데,롯데,06-26,넥센,L 3:9,9,PH,...,0,0,0.150,0.190,0.300,0.490,6,0.42,-0.26,-0.011
78301,황진수,1989-02-15,2018,롯데,롯데,06-27,넥센,W 9:8,7,SS,...,0,0,0.182,0.217,0.364,0.581,5,2.38,0.68,0.232
78302,황진수,1989-02-15,2018,롯데,롯데,06-28,넥센,W 8:6,9,3B,...,0,0,0.182,0.217,0.364,0.581,0,0.00,0.00,0.000
78303,황진수,1989-02-15,2018,롯데,롯데,06-30,@한화,L 5:6,8,PH,...,0,0,0.167,0.200,0.333,0.533,13,0.57,-0.52,-0.028