In [1]:
## import modules
import numpy as np
import pandas as pd

In [2]:
## set your path where your data are saved
fpath = 'C:/Users/ahn92/Documents/Sources/BDP\/'

In [5]:
def getSimFromTsv(fname = None , outfname = None):
    ## file input term
    if fname == None:
        fname = input('Input your input file name : ')
    inFile = pd.read_csv(fpath+fname, sep ='\t', header = None, encoding = 'UTF8')
    ## make the dictionary by using pivot
    usrName = set(inFile.iloc[:,0])
    catName = set(inFile.iloc[:,1])
    
    pdict = inFile.pivot(index = 0, columns = 1 , values= 2)
    pDict = pdict.to_dict()
    
    ## remove the nan term
    rmNandict = dict()
    for i in pDict.keys():
        my_dict = pDict[i]
        clean_dict = {k: my_dict[k] for k in my_dict if not np.isnan(my_dict[k])}
        rmNandict.update({i:clean_dict})
    
    ## we calculate the distance if data has same key
    ## get the same key fuction
    def getSameKey(key1,key2,dt):
        skey = []
        for i in dt[key1].keys():
            for j in dt[key2].keys():
                   if i==j:
                        skey.append(i)
        return(skey)
    
    ## calculate similarity function
    def calcSim(key1,key2,dt):
        tmpSum = 0
        if getSameKey(key1,key2,dt)==[]:
            return(np.nan)
        else:
            for i in getSameKey(key1,key2,dt):
                tmpSum = tmpSum + (dt[key1][i]-dt[key2][i])**2
            return(1/(1+np.sqrt(tmpSum)))
    
    ## output term
    outlst = []
    for i in rmNandict.keys():
        for j in rmNandict.keys():
            if i!=j and (not np.isnan(calcSim(i,j,rmNandict))):
                outlst.append([i,j,calcSim(i,j,rmNandict)])

    outdt = pd.DataFrame(outlst)  
    if outfname==None:
        outfname = input('input your output file name : ')
    outdt.to_csv(outfname, sep = '\t',index=False, header = False)
    return outdt

In [6]:
getSimFromTsv('in.txt','out.txt')

        0       1         2
0   Apple   Mango  0.333333
1   Apple  Orange  0.261204
2   Mango   Apple  0.333333
3   Mango  Orange  1.000000
4  Orange   Apple  0.261204
5  Orange   Mango  1.000000

In [7]:
getSimFromTsv('user_book_score_test.txt','user_book_score_test_out.txt')

                                0                              1         2
0                       글꽃 하나 피었네                        세도나 메서드  1.000000
1                       글꽃 하나 피었네                   소잉 하루에 VOL.3  0.333333
2                       글꽃 하나 피었네                   소잉 하루에 VOL.4  0.500000
3                       글꽃 하나 피었네                      커피 마스터클래스  0.261204
4                꽃이 지고 나면 잎이 보이듯이  무탄트 메시지(그곳에선 나 혼자만 이상한 사람이었다)  0.500000
5                꽃이 지고 나면 잎이 보이듯이                      커피 마스터클래스  0.333333
6              네팔 - LONELY PLANET                      커피 마스터클래스  0.500000
7   무탄트 메시지(그곳에선 나 혼자만 이상한 사람이었다)               꽃이 지고 나면 잎이 보이듯이  0.500000
8   무탄트 메시지(그곳에선 나 혼자만 이상한 사람이었다)                      커피 마스터클래스  0.500000
9                 반지의 얼렁뚱땅 비밀일기 5             쭉쭉 읽어라 중학초급 (2011)  0.500000
10                        세도나 메서드                      글꽃 하나 피었네  1.000000
11                   소잉 하루에 VOL.3                      글꽃 하나 피었네  0.333333
12                   소잉 하루에 VOL.3                   소잉 하루에 VOL.4  0.500000
13                   소잉 하루에 VOL.3                      커피 마스터클래스  1.000000
14                   소잉 하루에 VOL.4                      글꽃 하나 피었네  0.500000
15                   소잉 하루에 VOL.4                   소잉 하루에 VOL.3  0.500000
16                   소잉 하루에 VOL.4                      커피 마스터클래스  0.500000
17             쭉쭉 읽어라 중학초급 (2011)                반지의 얼렁뚱땅 비밀일기 5  0.500000
18                      커피 마스터클래스                      글꽃 하나 피었네  0.261204
19                      커피 마스터클래스               꽃이 지고 나면 잎이 보이듯이  0.333333
20                      커피 마스터클래스             네팔 - LONELY PLANET  0.500000
21                      커피 마스터클래스  무탄트 메시지(그곳에선 나 혼자만 이상한 사람이었다)  0.500000
22                      커피 마스터클래스                   소잉 하루에 VOL.3  1.000000
23                      커피 마스터클래스                   소잉 하루에 VOL.4  0.500000